module.exports = {
    dev: {
        js: [
            '/client/js/Core/namespace.js',
            '/client/js/Ui/namespace.js',
            '/client/js/Utils/sc_keynodes.js',
            '/client/js/Utils/utils.js',
            '/client/js/Utils/sc_helper.js',
            '/client/js/Utils/stringview.js',
            '/client/js/Utils/cache.js',
            '/client/js/Utils/sctp.js',
            '/client/js/Utils/fqueue.js',
            '/client/js/Utils/binary.js',
            '/client/js/Utils/triples.js',
            '/client/js/Utils/logUtils.js',
            '/client/js/Core/debug.js',
            '/client/js/Core/main.js',
            '/client/js/Core/server.js',
            '/client/js/Core/arguments.js',
            '/client/js/Core/componentsandbox.js',
            '/client/js/Core/translation.js',
            '/client/js/Core/componentmanger.js',
            '/client/js/Core/eventmanager.js',
            '/client/js/Ui/core.js',
            '/client/js/Ui/menu.js',
            'client/js/Ui/ContextSwitcher.js',
            '/client/js/Ui/eekbPanel.js',
            '/client/js/Ui/langpanel.js',
            '/client/js/Ui/locker.js',
            '/client/js/Ui/searchpanel.js',
            '/client/js/Ui/KeyboardHandler.js',
            '/client/js/Ui/taskpanel.js',
            '/client/js/Ui/argumentspanel.js',
            '/client/js/Ui/windowmanager.js',
            '/client/js/Ui/OpenComponentHandler.js',
            '/client/js/Ui/userpanel.js',
            "http://localhost:8080/skewer",
            "/static/components/js/scs/scs.js",
            "/static/components/js/scg/scg.js",
            "/static/components/js/image/image.js",
            "/static/components/js/txt/txt.js",
            "/static/components/js/html/html.js",
            "/static/components/js/youtube/youtubelink.js",
            "/static/components/js/map/googlemaplink.js",
            "/static/components/js/github/github.js",
            "/static/components/js/pdf/pdf.js",
            "/static/components/js/file-saver/FileSaver.min.js",
            "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.js"
        ],
        css: [
            "/static/components/css/scg.css",
            "/static/components/css/scs.css",
            "/static/components/css/html.css",
            "/static/components/css/github.css",
            "/client/css/core.css",
            "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.css", "/static/components/css/github.css"
        ]
    },
    current: {
        js: [
            "/static/components/js/sc-web-core.js",
            "/static/components/js/scs/scs.js",
            "/static/components/js/scg/scg.js",
            "/static/components/js/image/image.js",
            "/static/components/js/txt/txt.js",
            "/static/components/js/html/html.js",
            "/static/components/js/youtube/youtubelink.js",
            "/static/components/js/map/googlemaplink.js",
            "/static/components/js/github/github.js",
            "/static/components/js/pdf/pdf.js",
            "/static/components/js/file-saver/FileSaver.min.js",
        ],
        css: [
            "/static/components/css/scg.css",
            "/static/components/css/scs.css",
            "/static/components/css/html.css",
            "/static/components/css/github.css",
        ]
    }
}